version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    container_name: postgres-mmgmt
    image: postgres:latest
    environment:
      POSTGRES_DB: mmgmt
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  # PgAdmin - PostgreSQL Management UI
  pgadmin:
    container_name: pgadmin-mmgmt
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

  # RabbitMQ - Message Broker
  rabbitmq:
    container_name: rabbitmq-mmgmt
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Redis - Caching & Session Store
  redis:
    container_name: redis-mmgmt
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
